# Exercise 0.2 -  Numpy
prepared by M.Hauser

`numpy` is *the* fundamental package for scientific computing with Python. It provides fast (matlab-like) multi-dimensional-arrays (nd-arrays), which contain uniform data types with an arbitrary number of dimensions. It also provides many mathematical functions (`mean`, `std`, ...) and array methods (slicing, broadcasting, ...).

In [2]:
# numpy is generally abbreviated as np

import numpy as np

This course is not about processing data - we will mostly use data that was already prepared and is stored in netCDF format (see later exercises). However, one function to create data that we will use is `np.arange`


## np.arange

`np.arange` creates evenly spaced values within a given interval. 

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

This created an array with 10 elements. Notice how it starts at 0 and ends at 9.

The array has one dimension:

In [4]:
np.arange(10).shape

(10,)

`arange` stands for 'a range' (i.e. not for arrange). The call signature is

`np.arange(stop)`

`np.arange(start, stop)`


`np.arange(start, stop, step)`


### Exercise

 * Create an array with elements from 1 to 12

### Solution

In [5]:
np.arange(1, 13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

It can be a bit confusing that you need to set `stop = 13` for this array - but you'll get used to it. This also holds when you set `step`:

In [6]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

### Exercise
 * create a array from 0 to 5 in steps of 0.5

### Solution

In [7]:
np.arange(0, 5.1, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

## Other ways to create arrays

Arrays can be created in several ways

#### from a list

In [9]:
# with a list
a = np.asarray([1, 2, 3])

print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

# only the last command in the cell yields an output
a

(3,)
3
1
int64


array([1, 2, 3])

#### array with random values

In [10]:
# a 2d vector of random numbers

y = np.random.rand(3, 5)

print(y.shape)
print(y.size)
print(y.ndim)
# note the different dtype 
print(y.dtype)

y

(3, 5)
15
2
float64


array([[0.28281061, 0.65952178, 0.28564581, 0.8423726 , 0.72356526],
       [0.301543  , 0.98411997, 0.81722658, 0.81946467, 0.56514587],
       [0.73476339, 0.39015458, 0.68799329, 0.01163782, 0.09614595]])

#### array of zeros, ones, and identity matrix

In [11]:
# other ways to create arrays

y = np.zeros((1, 3))
print(y)
print('')

y = np.ones((2, 2)) * 3.1
print(y)
print('')


# identity matrix
y = np.eye(3)
print(y)

[[0. 0. 0.]]

[[3.1 3.1]
 [3.1 3.1]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Yes, the syntax is not entirely consistent: you do `np.random.rand(3, 4)` but `np.zeros((3, 4))`.

### Exercises

1. Create an array from a tuple: e.g.: `t = (1, 2, 3)`
* `np.random.rand` creates uniformly distributed numbers in `[0, 1)`. Can you create random integers between 0 and 55? Hint: `np.random.randint?`. (There are other ways, of course.)
* Can you create random numbers from a normal distribution? Hint: `np.random.ra<Tab>`.

### Solution

In [12]:
# 1
t = (1, 2, 3)
t = np.asarray(t)
print(t)

# 2
print(np.random.randint(0, 56))
print(int(np.random.rand() * 55))

# 3
np.random.randn()

[1 2 3]
4
46


-1.1664150116857956

## Array indexing

arrays are indexed with square brackets

#### Create 1D array

In [13]:
# create an array from 0..49 with shape (50)
x_1d = np.arange(50)
print(x_1d.shape)
print(x_1d)

(50,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


#### Get one element - as number, using `x[0]`

In [14]:
print("The value:", x_1d[0])
print('The shape:', x_1d[0].shape)
print('The type:', type(x_1d[0]))
print("It's not a ndarray!")

The value: 0
The shape: ()
The type: <class 'numpy.int64'>
It's not a ndarray!


#### Get one element - as array, using `x[0:1]`

In [ ]:
print("The value:", x_1d[0:1])
print('The shape:', x_1d[0:1].shape)
print('The type:', type(x_1d[0:1]))
print("It's a ndarray!")

#### Get the first ten elements

In [ ]:
print("x[0:10]:", x_1d[0:10])
print("x[:10]:", x_1d[:10])

#### Get the last element(s)

In [ ]:
print("Get the last element:")
print(x_1d[-1])

print("Get the last ten elements:")
print(x_1d[-10:])

#### Create 2D array

In [ ]:
# create an array from 0..50 with shape (5, 10)
x_2d = np.arange(50).reshape(5, 10)
print(x_2d.shape)
x_2d

#### Get the first row

In [ ]:
x_2d[0, :]

#### Get the last column (1D)

In [ ]:
x_2d[:, -1]

#### Get the first element

In [ ]:
x_2d[0, 0]

#### Looping through the 2D array - this happens row by row

In [ ]:
for i in x_2d:
    print(i)

#### Looping through a 1D array - this happens element by element

In [ ]:
for i in x_2d.flat[:5]:
    print(i)

## Calculations

You can do all sorts of calculations. Usually they are the done element-by-element.

#### create 2 random arrays

In [ ]:
x = np.random.rand(3, 5)
y = np.random.rand(3, 5)
print(x)

#### add both arrays - this is done element by element

In [ ]:
z = x + y

z

#### a scalar is added to all elements

In [ ]:
# add a scalar
x = x + 1

x

### functions

numpy offers all sorts of mathematical functions, e.g. the `mean`

#### Mean of all elements

In [ ]:
y.mean()

#### Mean over all rows

In [ ]:
y.mean(axis=0)

#### Mean over all columns

In [ ]:
y.mean(axis=1)

### Exercise

Calculate the standard deviation of

 * the whole array
 * the rows 
 * the columns

### Solution

#### all elements

In [ ]:
y.std()

#### all rows

In [ ]:
y.std(axis=0)

#### all columns

In [ ]:
print(y.std(axis=1))

## Broadcasting

Broadcasting can be very helpful as it allows to add arrays with different shapes.

In [ ]:
# create 2 arrays
x = np.arange(15).reshape(3, -1)
y = np.asarray([0.1, 0.2, 0.3, 0.4, 0.5])

print('x.shape:', x.shape)
print('y.shape:', y.shape)

although `x` and `y` do not have the same shape, we can add them:

In [ ]:
x + y